# Run `pre-commit install` to install pre-commit into your git hooks.
repos:
    - repo: local
      hooks:
          - id: checkstyle
            name: Checkstyle
            entry: linter/run_checkstyle.bat
            language: script
            files: \.java$
