name: pre-commit
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  linux:
    name: pre-commit-linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Check format
      run: mvn spotless:check
    - uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - name: Make run_checkstyle.py executable
      run: chmod +x linter/run_checkstyle.py
    - name: Make run_checkstyle.sh executable
      run: chmod +x linter/run_checkstyle.sh
    - uses: pre-commit/action@v3.0.1
